version: '3'
services:
  buhocenter-postgres:
    image: "postgres:9.6-alpine"
    container_name: buhocenter-postgres
    volumes:
      - buhocenter-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: buhocenter
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_HOST_AUTH_METHOD: "trust"

  buhocenter-backend:
    build: ./buhocenter-backend
    expose:
      - 3000
    environment:
        API_PREFIX: '/api/v1'
        TYPEORM_CONNECTION: 'postgres'
        TYPEORM_HOST: buhocenter-postgres
        TYPEORM_PORT: '5432'
        TYPEORM_USERNAME: postgres
        TYPEORM_PASSWORD: 1234
        TYPEORM_DATABASE: 'buhocenter'
        TYPEORM_ENTITIES: 'dist/**/*.entity.js'
        TYPEORM_SYNCHRONIZE: 'true'
        TYPEORM_LOGGING: 'false'
        SENDGRID_API_KEY: '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'
        UTRUST_ENDPOINT: 'https://merchants.api.sandbox-utrust.com/api'
        UTRUST_API_KEY: 'u_test_api_84c27c02-f780-4022-8474-ffecd468e55f'
        UTRUST_WEBHOOK_SECRET: 'u_test_webhooks_be6d3283-494a-4e5d-bec8-6e45c658db18'
        UTRUST_RETURN_URL: '/payments/return'
        UTRUST_CALLBACK_URL: '/payments/update'
        UTRUST_CANCEL_URL: '/payments/cancel'
        POEDITOR_API_KEY: '7594e4bec91ddcd0c945341dfbe92c0e'
        POEDITOR_PROJECT_ID: '341725'
        JWT_SECRET: 'bUH0cE3Nt3Er-e3Ec0OmeE3rcE3@1.0.0'
        JWT_EXPIRES_IN: '12h'
        SMARTSTREET_AUTH_KEY: 018e48c3-9ab3-4ea4-1f51-62a3c351c9a5
        SMARTSTREET_AUTH_TOKEN: rutHqaVC3bklTQiZHWYW
        DIRECTION_VERIFICATION_URL: https://us-street.api.smartystreets.com/street-address      
    ports:
      - 3000:3080
    links:
      - buhocenter-postgres
    volumes:
      - ./buhocenter-backend/src
    command: npm run start

  buhocenter-frontend:
    build: ./buhocenter-frontend
    environment:
      VUE_APP_BUHOCENTER_API_UR: http://localhost:3000
      VUE_APP_BUHOCENTER_API_PREFI: /api/v1
      VUE_APP_BUHOCENTER_FIREBASE_API_KE: AIzaSyDAF-RBZ8PwnxOaYIaPV4s9Z7eqVPOFyNM
      VUE_APP_BUHOCENTER_FIREBASE_AUTH_DOMAI: buhocenter.firebaseapp.com
      VUE_APP_BUHOCENTER_FIREBASE_DB_UR: https://buhocenter.firebaseio.com
      VUE_APP_BUHOCENTER_FIREBASE_PROJECT_I: buhocenter
      VUE_APP_BUHOCENTER_FIREBASE_STORAGE_BUCKE: buhocenter.appspot.com
      VUE_APP_BUHOCENTER_FIREBASE_MS_I: 205448199268
      VUE_APP_BUHOCENTER_FIREBASE_APP_I:1: 205448199268:web:5f12aa31eedf3694fa7371
      VUE_APP_BUHOCENTER_FIREBASE_MEASUREMENT_I: G-4F0Q6HBPSE
    expose:
      - 8081
    ports:
      - 8081:8080
    volumes:
      - ./buhocenter-frontend/src
    links:
      - buhocenter-backend
    command: npm run serve

volumes:
  buhocenter-data:
